[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "sofia-ada-lyra"
version = "0.1.0"
description = "Sofía Ada Lyra"
requires-python = ">=3.12"
dependencies = [
    "ollama",
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
python_classes = ["*Test"]