"""Message-matrix coordination contracts and shadow-mode tracing."""
from .classifier import BaselineTurnClassifier
from .routing_plan import MatrixRoutingPlanner
from .privacy import MatrixPrivacyPlanner
from .tool_exposure import MatrixToolExposurePlanner
from .response import MatrixResponsePlanner, MatrixResponseValidator
from .evidence import MatrixEvidencePlanner, MatrixEvidenceResolver
from .authority import MatrixAuthorityPlanner
from .context_plan import MatrixContextPlanner
from .coordinator import (
    MatrixCoordinator,
    MatrixDomainEvaluator,
    MatrixRegistry,
    TurnClassifier,
)
from .model import (
    MATRIX_SCHEMA_VERSION,
    AuthorityDecision,
    AuthorityPlan,
    CognitionExecutionStep,
    CognitionExecutionTrace,
    ContextPlan,
    DomainContribution,
    EvidenceKind,
    EvidenceMatrix,
    EvidenceRecord,
    EvidenceRequirement,
    EvidenceState,
    HistoryPolicy,
    MatrixConfidence,
    MatrixDomain,
    MatrixIntent,
    MatrixRelevance,
    MatrixRoute,
    MatrixTrace,
    ResponseContract,
    ResponseStrategy,
    ResponseValidation,
    ResponseValidationDisposition,
    RoutingPlan,
    PrivacyProjectionPlan,
    ToolExposurePlan,
    TurnEnvelope,
    TurnMatrix,
)
from .trace import MatrixTraceStore

__all__ = [
    "MATRIX_SCHEMA_VERSION",
    "AuthorityDecision",
    "AuthorityPlan",
    "BaselineTurnClassifier",
    "CognitionExecutionStep",
    "CognitionExecutionTrace",
    "ContextPlan",
    "DomainContribution",
    "EvidenceKind",
    "EvidenceMatrix",
    "EvidenceRecord",
    "EvidenceRequirement",
    "EvidenceState",
    "HistoryPolicy",
    "MatrixConfidence",
    "MatrixCoordinator",
    "MatrixContextPlanner",
    "MatrixDomain",
    "MatrixDomainEvaluator",
    "MatrixIntent",
    "MatrixRegistry",
    "MatrixRelevance",
    "MatrixAuthorityPlanner",
    "MatrixEvidencePlanner",
    "MatrixEvidenceResolver",
    "MatrixResponsePlanner",
    "MatrixResponseValidator",
    "MatrixRoutingPlanner",
    "MatrixPrivacyPlanner",
    "MatrixToolExposurePlanner",
    "MatrixRoute",
    "RoutingPlan",
    "PrivacyProjectionPlan",
    "ToolExposurePlan",
    "MatrixTrace",
    "MatrixTraceStore",
    "ResponseContract",
    "ResponseStrategy",
    "ResponseValidation",
    "ResponseValidationDisposition",
    "TurnClassifier",
    "TurnEnvelope",
    "TurnMatrix",
]
