"""Message-matrix coordination contracts and shadow-mode tracing."""
from .classifier import BaselineTurnClassifier
from .context_plan import MatrixContextPlanner
from .coordinator import (
    MatrixCoordinator,
    MatrixDomainEvaluator,
    MatrixRegistry,
    TurnClassifier,
)
from .model import (
    MATRIX_SCHEMA_VERSION,
    AuthorityDecision,
    AuthorityPlan,
    ContextPlan,
    DomainContribution,
    EvidenceKind,
    EvidenceMatrix,
    EvidenceRecord,
    EvidenceRequirement,
    EvidenceState,
    HistoryPolicy,
    MatrixConfidence,
    MatrixDomain,
    MatrixIntent,
    MatrixRelevance,
    MatrixTrace,
    ResponseContract,
    ResponseStrategy,
    ResponseValidation,
    ResponseValidationDisposition,
    TurnEnvelope,
    TurnMatrix,
)
from .trace import MatrixTraceStore

__all__ = [
    "MATRIX_SCHEMA_VERSION",
    "AuthorityDecision",
    "AuthorityPlan",
    "BaselineTurnClassifier",
    "ContextPlan",
    "DomainContribution",
    "EvidenceKind",
    "EvidenceMatrix",
    "EvidenceRecord",
    "EvidenceRequirement",
    "EvidenceState",
    "HistoryPolicy",
    "MatrixConfidence",
    "MatrixCoordinator",
    "MatrixContextPlanner",
    "MatrixDomain",
    "MatrixDomainEvaluator",
    "MatrixIntent",
    "MatrixRegistry",
    "MatrixRelevance",
    "MatrixTrace",
    "MatrixTraceStore",
    "ResponseContract",
    "ResponseStrategy",
    "ResponseValidation",
    "ResponseValidationDisposition",
    "TurnClassifier",
    "TurnEnvelope",
    "TurnMatrix",
]
